config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  resources :projects do

    resources :tasks, controller: 'project/tasks' do
      member do
        get :details
        patch :toggle_done
        patch :toggle_star

        get :changes
      end

      collection do
        get :completed
      end

      resources :comments, controller: 'project/comments', only: [:create, :destroy]
    end

    resources :links, controller: 'project/links', only: [:index, :new, :create, :show, :destroy]
    resources :notes, controller: 'project/notes' do
      member do
        get :history
        get :version
      end
    end

    resources :files, controller: 'project/files', only: [:index, :new, :create] do
      collection do
        get :download
        delete :destroy, as: 'delete'
      end
    end

    resources :users, only: [:index, :destroy], controller: 'project/users' do
      collection do
        get 'invite', to: 'project/users#invite'
        post 'add_member', to: 'project/users#add_member'
        delete 'leave', to: 'project/users#leave'
      end
    end

    resource :pins, controller: 'project/pins', only: [:create, :destroy]

    resource :activity, only: :show, controller: 'project/activity'

    resource :import, only: [:new, :create, :show], controller: 'project/import'
    resource :export, only: [:new, :create], controller: 'project/export'
  end

  namespace :admin do
    resources :users, only: [:index, :show, :edit, :update, :destroy]
  end

  get 'admin' => 'admin#index'
  get 'admin/activity', to: 'admin/activity#index'

  namespace :users do
    resource :settings, only: [:show, :update]
    resource :account, only: [:show, :update, :destroy]
  end
  get 'users/:id/avatar', to: 'users/avatars#show', as: :user_avatar

  get 'projects/:id/schedule', to: redirect { |params, _| "/projects/#{params[:id]}" }
  get 'schedule', to: redirect('/tasks')
  get 'search', to: 'search#index'
  resources :tasks, only: :index, controller: 'tasks' do
    member do
      patch :toggle_done
    end
  end

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  get "hello" => "hello#welcome"

  # Defines the root path route ("/")
  root "projects#index"
end

app/controllers/project/activity_controller.rb
class Project::ActivityController < Project::BaseController
  PER_PAGE = 100

  def show
    @tab_name = 'Activity'

    @records = project.activities.includes(:user).order(id: :desc).page(params[:page]).per(PER_PAGE)
  end
end

app/controllers/project/base_controller.rb
class Project::BaseController < ApplicationController
  before_action :authenticate_user!
  before_action :project
  before_action :authorize_access

  layout 'project'

  def project
    @project ||= Project.find(params[:project_id])
  end
end

app/controllers/project/comments_controller.rb
class Project::CommentsController < Project::BaseController
  before_action :set_task

  def create
    @comment = @task.comments.build(comment_params)
    @comment.user = current_user

    if @comment.save
      @project.add_activity(current_user, 'commented on', @task)

      respond_to do |format|
        format.html { redirect_to task_path, notice: 'Comment was successfully created.' }
        format.turbo_stream
      end
    else
      respond_to do |format|
        format.html { redirect_to task_path, alert: 'Comment could not be created.' }
      end
    end
  end

  def destroy
    @comment = @task.comments.find(params[:id])
    @comment.update(removed_at: Time.current)

    respond_to do |format|
      format.html { redirect_to task_path, notice: 'Comment was successfully deleted.' }
      format.turbo_stream
    end
  end

  private

  def set_task
    @task = project.tasks.find(params[:task_id])
  end

  def comment_params
    permitted = params.require(:comment).permit(:body, :attachment)
    permitted.delete(:attachment) unless file_storage_enabled?
    permitted
  end

  def task_path
    details_project_task_path(project, @task)
  end
end

app/controllers/project/export_controller.rb
class Project::ExportController < Project::BaseController
  before_action :project_owner_only!

  def new
  end

  def create
    export_service = ProjectExportService.new(project)

    respond_to do |format|
      format.json do
        send_data export_service.export_data.to_json,
                  filename: export_service.filename,
                  type: 'application/json',
                  disposition: 'attachment'
      end
    end
  end
end

app/controllers/project/files_controller.rb
class Project::FilesController < Project::BaseController
  before_action :set_tab
  before_action :require_file_storage!, only: [:new, :create]

  def index
  end

  def new
  end

  def download
    file = project.project_files.find { |f| f.identifier == params[:file] }

    if file
      if ENV['AWS_S3_BUCKET'].present?
        send_data file.read, filename: file.identifier, type: file.content_type, disposition: 'attachment'
      else
        send_file file.file.path, filename: file.file.identifier, type: file.file.content_type, disposition: 'attachment'
      end
    else
      redirect_to project_path(project), alert: 'File not found.'
    end
  end

  def create
    add_more_files(params[:project][:project_files])

    if project.save
      redirect_to project_files_path(@project), notice: 'Files were successfully uploaded.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    remove_file(params[:file])

    project.save

    respond_to do |format|
      format.html { redirect_to project_files_path(@project) }
      format.json { head :no_content }
    end
  end

  private

  def project_params
    params.require(:project).permit({ project_files: [] })
  end

  def add_more_files(new_files)
    existing_files = project.project_files || []
    project.project_files = existing_files.map(&:identifier) + new_files
  end

  def remove_file(file_name)
    remain_project_files = project.project_files.reject { |f| f.identifier == file_name }

    if remain_project_files.size != project.project_files.size
      project.project_files = remain_project_files.map(&:identifier)
    end
  end

  def set_tab
    @tab_name = 'Project'
  end
end

app/controllers/project/import_controller.rb
class Project::ImportController < Project::BaseController
  before_action :project_owner_only!

  def show
    @imported_tasks = project.tasks.where(id: import_session_data(:task_ids))
    @imported_task_count = import_session_data(:task_count)
    @imported_note_count = import_session_data(:note_count)
    @imported_comment_count = import_session_data(:comment_count)
  end

  def new
  end

  def create
    file = params[:file]
    data = parse_json_file(file)

    validator = ProjectImportValidator.new(file, data)

    unless validator.valid?
      redirect_to new_project_import_path(project), alert: validator.errors.first
      return
    end

    perform_import(data)
  rescue JSON::ParserError
    redirect_to new_project_import_path(project), alert: 'Invalid JSON file.'
  rescue ActiveRecord::RecordInvalid => e
    redirect_to new_project_import_path(project), alert: e.message
  rescue ProjectImportService::ImportFormatError => e
    redirect_to new_project_import_path(project), alert: e.message
  rescue StandardError
    redirect_to new_project_import_path(project),
                alert: 'An error occurred during import. Please try again.'
  end

  private

  def parse_json_file(file)
    return nil if file.nil?

    JSON.parse(file.read)
  end

  def perform_import(data)
    import_service = ProjectImportService.new(project, data, current_user)
    import_service.import!

    store_import_stats(import_service.import_stats)

    redirect_to project_import_path(project), notice: 'Data imported successfully.'
  end

  def store_import_stats(stats)
    session[:imported_task_ids] = stats[:task_ids]
    session[:imported_task_count] = stats[:task_count]
    session[:imported_note_count] = stats[:note_count]
    session[:imported_comment_count] = stats[:comment_count]
  end

  def import_session_data(key)
    session.delete("imported_#{key}".to_sym) || default_value_for(key)
  end

  def default_value_for(key)
    key == :task_ids ? [] : 0
  end
end

app/controllers/project/links_controller.rb
class Project::LinksController < Project::BaseController
  before_action :set_link, only: %i[ show destroy ]
  before_action :set_tab

  def index
  end

  def show
  end

  def new
    @link = Link.new
  end

  def create
    @link = project.links.new(link_params)
    @link.user = current_user

    respond_to do |format|
      if @link.save
        format.html { redirect_to project_links_path(@project), notice: "Link was successfully created." }
        format.json { render :show, status: :created, location: @link }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @link.destroy!

    respond_to do |format|
      format.html { redirect_to project_links_path(@project) }
      format.json { head :no_content }
    end
  end

  private

  def set_link
    @link = project.links.find(params[:id])
  end

  def link_params
    params.require(:link).permit(:title, :url, :user_id, :project_id)
  end

  def set_tab
    @tab_name = 'Project'
  end
end

app/controllers/project/notes_controller.rb
class Project::NotesController < Project::BaseController
  before_action :set_note, only: %i[ show destroy edit update history version]
  before_action :set_tab, only: %i[ show edit index history version ]

  def index
  end

  def show
  end

  def history
    @versions = @note.versions.order(created_at: :desc)

    user_ids = @versions.map(&:whodunnit)
    user_ids.compact!
    user_ids.uniq!
    users_by_id = User.where(id: user_ids).index_by(&:id)

    @users_by_version = @versions.each_with_object({}) do |version, hash|
      hash[version.id] = users_by_id[version.whodunnit.to_i]
    end
  end

  def version
    @version = @note.versions.find(params[:version_id])
  end

  def new
    @note = project.notes.new(title: 'New Note')
    @note.user = current_user

    if @note.save
      @project.add_activity(current_user, 'created', @note)

      redirect_to edit_project_note_path(@project, @note)
    else
      record_not_found
    end
  end

  def edit
  end

  def update
    @note.update(note_params)

    respond_to do |format|
      format.html { redirect_to edit_project_note_path(@project, @note), notice: 'Saved' }
    end
  end

  def destroy
    @note.destroy!
    @project.add_activity(current_user, 'removed', @note)

    respond_to do |format|
      format.html { redirect_to project_notes_path(@project) }
      format.json { head :no_content }
    end
  end

  private

  def set_note
    @note = project.notes.find(params[:id])
  end

  def set_tab
    @tab_name = 'Project'
  end

  def note_params
    params.require(:note).permit(:title, :content)
  end
end

app/controllers/project/pins_controller.rb
class Project::PinsController < Project::BaseController
  def create
    current_user.pinned_projects << project unless current_user.pinned_projects.include?(project)

    redirect_to project_path(project), notice: "Project pinned successfully."
  end

  def destroy
    current_user.pinned_projects.delete(project)

    redirect_to project_path(project), notice: "Project unpinned successfully."
  end
end

app/controllers/project/users_controller.rb
class Project::UsersController < Project::BaseController
  before_action :not_personal
  before_action :project_owner_only!, except: [:index, :leave]
  before_action :set_tab

  def index
    @recent_activity = project.activities.includes(:user).order(id: :desc).limit(20)
  end

  def invite
  end

  def add_member
    user = User.find_by(email: params[:email])

    if user
      if user.allow_invites
        if project.user != user && project.users.exclude?(user)
          if project.users << user
            project.add_activity(current_user, 'invited', user)

            redirect_to project_users_path(project)
            return
          else
            error = 'User could not be added.'
          end
        else
          error = 'User is already added to the project'
        end
      else
        error = 'User disabled invitations'
      end
    else
      error = 'User not found'
    end

    redirect_to invite_project_users_path(@project), alert: error
  end

  def destroy
    user = User.find(params[:id])

    if project.users.include?(user)
      project.users.delete(user)

      redirect_to project_users_path(project), notice: 'User was successfully removed.'
    else
      redirect_to project_users_path(project), alert: 'User could not be found or removed.'
    end
  end

  def leave
    if project.users.include?(current_user)
      project.users.delete(current_user)

      redirect_to projects_path, notice: 'You left the project.'
    end
  end

  private

  def not_personal
    redirect_to root_path if project.personal?
  end

  def set_tab
    @tab_name = 'Team'
  end
end

app/helpers/files_helper.rb
module FilesHelper
  def allowed_img_file_types
    %w(
      image/jpeg
      image/gif
      image/png
    ).join(',')
  end

  def allowed_file_types
    %w(
      text/plain
      image/jpeg
      image/gif
      image/png
      application/pdf
      application/msword
      application/vnd.ms-excel
      application/vnd.openxmlformats-officedocument.spreadsheetml.sheet
      application/vnd.openxmlformats-officedocument.wordprocessingml.document
    ).join(',')
  end

  def s3_storage?
    Rails.application.config.app_settings[:aws_s3_bucket].present?
  end

  def file_storage_enabled?
    s3_storage? || Rails.application.config.app_settings[:enable_local_file_storage]
  end

  def project_file_field(f)
    f.file_field :project_files,
                 multiple: true, required: true,
                 accept: allowed_file_types,
                 class: "appearance-none file-select w-full
            leading-tight file:mr-5 file:py-2 file:px-4
            file:rounded-md file:border-0
            file:text-sm file:font-medium"
  end

  def styled_file_field(f, name)
    f.file_field name.to_sym,
                 multiple: false, required: false,
                 accept: allowed_file_types,
                 class: "appearance-none file-select w-full text-sm
            leading-tight file:mr-5 file:py-2 file:px-4
            file:rounded-md file:border-0
            file:text-sm file:font-medium"
  end
end

app/helpers/project/export_helper.rb
module Project::ExportHelper
end

app/helpers/project/import_helper.rb
module Project::ImportHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
  def project_tabs(project, selected = nil)
    tabs = [
      { name: 'Project', path: project_path(project) },
      { name: 'Tasks', path: project_tasks_path(project) }
    ]

    unless project.personal?
      tabs << { name: 'Team', path: project_users_path(project) }
    end

    if project.user == current_user
      tabs << { name: 'Settings', path: edit_project_path(project) }
    end

    render_tabs(tabs, selected)
  end

  def project_nav_link(path, label, count = nil, compact: false)
    link_to path, class: "flex flex-col bg-gray-400/5 p-6 dark:bg-white/5" do
      content = tag.dt(label, class: "text-xs/5 font-semibold text-gray-600 dark:text-gray-300")

      unless compact
        content += tag.dd(count, class: "order-first text-2xl font-semibold tracking-tight text-gray-900 dark:text-white")
      end

      content
    end
  end
end

app/views/project/files/_file.html.erb
<li>
  <div class="flex items-center justify-between">
    <div class="flex items-center min-w-0">
      <!-- File type icon - dynamically choose based on file extension if possible -->
      <div class="flex-shrink-0 flex items-center justify-center">
        <% file_extension = File.extname(project_file.file.filename).downcase %>
        <% if %w[.jpg .jpeg .png .gif .svg].include?(file_extension) %>
          <!-- Image file icon -->
          <svg xmlns="http://www.w3.org/2000/svg" class="size-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="1" d="M4 16l4.586-4.586a2 2 0 012.828 0L16 16m-2-2l1.586-1.586a2 2 0 012.828 0L20 14m-6-6h.01M6 20h12a2 2 0 002-2V6a2 2 0 00-2-2H6a2 2 0 00-2 2v12a2 2 0 002 2z" />
          </svg>
        <% elsif %w[.pdf .doc .docx .txt .rtf].include?(file_extension) %>
          <!-- Document file icon -->
          <svg xmlns="http://www.w3.org/2000/svg" class="size-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="1" d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
          </svg>
        <% elsif %w[.zip .rar .tar .gz .7z].include?(file_extension) %>
          <!-- Archive file icon -->
          <svg xmlns="http://www.w3.org/2000/svg" class="size-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="1" d="M5 8h14M5 8a2 2 0 110-4h14a2 2 0 110 4M5 8v10a2 2 0 002 2h10a2 2 0 002-2V8m-9 4h4" />
          </svg>
        <% else %>
          <!-- Default file icon -->
          <svg xmlns="http://www.w3.org/2000/svg" class="size-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="1" d="M7 21h10a2 2 0 002-2V9.414a1 1 0 00-.293-.707l-5.414-5.414A1 1 0 0012.586 3H7a2 2 0 00-2 2v14a2 2 0 002 2z" />
          </svg>
        <% end %>
      </div>

      <div class="ml-4 min-w-0 flex-1">
        <div class="flex items-center">
          <%= link_to download_project_files_path(@project, file: project_file.identifier), data: { turbo: false }, class: "link-primary list-text-primary truncate" do %>
            <%= project_file.file.filename %>
          <% end %>
        </div>
        <div class="mt-1 flex items-center list-text-secondary">
          <span><%= number_to_human_size project_file.file.size %></span>
          <%
            # Try to get content type, handling both S3 and local storage
            content_type = if project_file.respond_to?(:content_type) && project_file.content_type.present?
                            project_file.content_type
                          elsif project_file.file.respond_to?(:content_type) && project_file.file.content_type.present?
                            project_file.file.content_type
                          end
          %>
          <% if content_type.present? %>
            <span class="mx-1">&middot;</span>
            <span><%= content_type %></span>
          <% end %>
        </div>
      </div>
    </div>

    <div class="flex-shrink-0 flex items-center space-x-2">
      <!-- Download button -->
      <%= link_to download_project_files_path(@project, file: project_file.identifier), data: { turbo: false }, class: "inline-flex items-center p-1.5", title: "Download" do %>
        <svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" />
        </svg>
      <% end %>

      <!-- Delete button -->
      <%= button_to delete_project_files_path(@project, file: project_file.identifier), method: :delete, data: { turbo_confirm: 'Delete the file? Are you sure?' }, alt: 'Delete file', class: "inline-flex items-center p-1.5", title: "Delete" do %>
        <svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16" />
        </svg>
      <% end %>
    </div>
  </div>
</li>

app/views/project/files/index.html.erb
<div class="">
  <div class="resource-container">
    <!-- Header with actions -->
    <div class="resource-header">
      <div>
        <h3 class="resource-title">Project Files</h3>
        <p class="resource-description">Upload and organize project-related files to keep all your resources in one place.</p>
      </div>
      <% if file_storage_enabled? %>
        <div>
          <%= link_to new_project_file_path(@project), class: "btn-base" do %>
            Add File
          <% end %>
        </div>
      <% end %>
    </div>

    <!-- File list -->
    <div class="bg-base">
      <% if !file_storage_enabled? %>
        <div class="resource-empty-state">
          <svg class="resource-empty-icon" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="1" d="M19.5 14.25v-2.625a3.375 3.375 0 00-3.375-3.375h-1.5A1.125 1.125 0 0113.5 7.125v-1.5a3.375 3.375 0 00-3.375-3.375H8.25m6.75 12H9m1.5-12H5.625c-.621 0-1.125.504-1.125 1.125v17.25c0 .621.504 1.125 1.125 1.125h12.75c.621 0 1.125-.504 1.125-1.125V11.25a9 9 0 00-9-9z" />
          </svg>
          <h3 class="resource-empty-title">File uploads disabled</h3>
          <p class="resource-empty-description">File storage is not configured. Configure S3 or enable local file storage to upload files.</p>
        </div>
      <% elsif @project.project_files.any? %>
        <ul role="list" class="resource-list">
          <% @project.project_files.each do |project_file| %>
            <%= render 'project/files/file', project_file: project_file %>
          <% end %>
        </ul>
      <% else %>
        <div class="resource-empty-state">
          <svg class="resource-empty-icon" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="1" d="M19.5 14.25v-2.625a3.375 3.375 0 00-3.375-3.375h-1.5A1.125 1.125 0 0113.5 7.125v-1.5a3.375 3.375 0 00-3.375-3.375H8.25m6.75 12H9m1.5-12H5.625c-.621 0-1.125.504-1.125 1.125v17.25c0 .621.504 1.125 1.125 1.125h12.75c.621 0 1.125-.504 1.125-1.125V11.25a9 9 0 00-9-9z" />
          </svg>
          <h3 class="resource-empty-title">No files</h3>
          <p class="resource-empty-description">Get started by uploading your first project file.</p>
          <div class="resource-empty-action">
            <%= link_to new_project_file_path(@project), class: "btn-base" do %>
              Upload a file
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/project/files/new.html.erb
<div class="sm:mx-auto sm:w-full sm:max-w-md">
  <%= form_for @project, url: project_files_path(project_id: @project.id), html: { multipart: true, method: :post, class: "contents" } do |f| %>
    <%= render "shared/errors", resource: @project %>

    <div class="shadow p-4 rounded-md border border-base bg-base">
      <%= f.label :project_files, class: "flex flex-col items-center justify-center w-full h-64 border-2 border-gray-300 dark:border-gray-700 dark:hover:border-gray-500 dark:hover:bg-gray-600 border-dashed rounded-lg cursor-pointer bg-gray-50 dark:bg-gray-950 hover:bg-gray-100 dark:hover:bg-gray-900 mb-4" do %>
        <svg class="w-8 h-8 mb-4 text-gray-500" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 20 16">
          <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 13h3a3 3 0 0 0 0-6h-.025A5.56 5.56 0 0 0 16 6.5 5.5 5.5 0 0 0 5.207 5.021C5.137 5.017 5.071 5 5 5a4 4 0 0 0 0 8h2.167M10 15V6m0 0L8 8m2-2 2 2"/>
        </svg>
        <p class="mb-2 text-sm text-gray-500"><span class="font-semibold">Click to upload</span></p>
        <p class="text-xs text-gray-500">Images and documents (Max. 5MB)</p>
      <% end %>

      <%= project_file_field(f) %>

      <div class="mt-4 border-t border-base pt-4">
        <% if s3_storage? %>
          <div class="mb-4">
            <p class="text-sm text-gray-400 dark:text-gray-600">
            Your app is configured to use aws s3 for file storage. If there are any errors with uploading, make sure your s3 env variables are set and correct.
            </p>
          </div>
        <% end %>

        <%= f.submit "Upload Files", class: "btn-base" %>
        <%= link_to 'Cancel', project_files_path(@project), class: 'btn-base float-right' %>
      </div>
    </div>
  <% end %>
</div>