config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  resources :projects do

    resources :tasks, controller: 'project/tasks' do
      member do
        get :details
        patch :toggle_done
        patch :toggle_star

        get :changes
      end

      collection do
        get :completed
      end

      resources :comments, controller: 'project/comments', only: [:create, :destroy]
    end

    resources :links, controller: 'project/links', only: [:index, :new, :create, :show, :destroy]
    resources :notes, controller: 'project/notes' do
      member do
        get :history
        get :version
      end
    end

    resources :files, controller: 'project/files', only: [:index, :new, :create] do
      collection do
        get :download
        delete :destroy, as: 'delete'
      end
    end

    resources :users, only: [:index, :destroy], controller: 'project/users' do
      collection do
        get 'invite', to: 'project/users#invite'
        post 'add_member', to: 'project/users#add_member'
        delete 'leave', to: 'project/users#leave'
      end
    end

    resource :pins, controller: 'project/pins', only: [:create, :destroy]

    resource :activity, only: :show, controller: 'project/activity'

    resource :import, only: [:new, :create, :show], controller: 'project/import'
    resource :export, only: [:new, :create], controller: 'project/export'
  end

  namespace :admin do
    resources :users, only: [:index, :show, :edit, :update, :destroy]
  end

  get 'admin' => 'admin#index'
  get 'admin/activity', to: 'admin/activity#index'

  namespace :users do
    resource :settings, only: [:show, :update]
    resource :account, only: [:show, :update, :destroy]
  end
  get 'users/:id/avatar', to: 'users/avatars#show', as: :user_avatar

  get 'projects/:id/schedule', to: redirect { |params, _| "/projects/#{params[:id]}" }
  get 'schedule', to: redirect('/tasks')
  get 'search', to: 'search#index'
  resources :tasks, only: :index, controller: 'tasks' do
    member do
      patch :toggle_done
    end
  end

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  get "hello" => "hello#welcome"

  # Defines the root path route ("/")
  root "projects#index"
end

app/controllers/project/activity_controller.rb
class Project::ActivityController < Project::BaseController
  PER_PAGE = 100

  def show
    @tab_name = 'Activity'

    @records = project.activities.includes(:user).order(id: :desc).page(params[:page]).per(PER_PAGE)
  end
end

app/controllers/project/base_controller.rb
class Project::BaseController < ApplicationController
  before_action :authenticate_user!
  before_action :project
  before_action :authorize_access

  layout 'project'

  def project
    @project ||= Project.find(params[:project_id])
  end
end

app/controllers/project/comments_controller.rb
class Project::CommentsController < Project::BaseController
  before_action :set_task

  def create
    @comment = @task.comments.build(comment_params)
    @comment.user = current_user

    if @comment.save
      @project.add_activity(current_user, 'commented on', @task)

      respond_to do |format|
        format.html { redirect_to task_path, notice: 'Comment was successfully created.' }
        format.turbo_stream
      end
    else
      respond_to do |format|
        format.html { redirect_to task_path, alert: 'Comment could not be created.' }
      end
    end
  end

  def destroy
    @comment = @task.comments.find(params[:id])
    @comment.update(removed_at: Time.current)

    respond_to do |format|
      format.html { redirect_to task_path, notice: 'Comment was successfully deleted.' }
      format.turbo_stream
    end
  end

  private

  def set_task
    @task = project.tasks.find(params[:task_id])
  end

  def comment_params
    permitted = params.require(:comment).permit(:body, :attachment)
    permitted.delete(:attachment) unless file_storage_enabled?
    permitted
  end

  def task_path
    details_project_task_path(project, @task)
  end
end

app/controllers/project/export_controller.rb
class Project::ExportController < Project::BaseController
  before_action :project_owner_only!

  def new
  end

  def create
    export_service = ProjectExportService.new(project)

    respond_to do |format|
      format.json do
        send_data export_service.export_data.to_json,
                  filename: export_service.filename,
                  type: 'application/json',
                  disposition: 'attachment'
      end
    end
  end
end

app/controllers/project/files_controller.rb
class Project::FilesController < Project::BaseController
  before_action :set_tab
  before_action :require_file_storage!, only: [:new, :create]

  def index
  end

  def new
  end

  def download
    file = project.project_files.find { |f| f.identifier == params[:file] }

    if file
      if ENV['AWS_S3_BUCKET'].present?
        send_data file.read, filename: file.identifier, type: file.content_type, disposition: 'attachment'
      else
        send_file file.file.path, filename: file.file.identifier, type: file.file.content_type, disposition: 'attachment'
      end
    else
      redirect_to project_path(project), alert: 'File not found.'
    end
  end

  def create
    add_more_files(params[:project][:project_files])

    if project.save
      redirect_to project_files_path(@project), notice: 'Files were successfully uploaded.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    remove_file(params[:file])

    project.save

    respond_to do |format|
      format.html { redirect_to project_files_path(@project) }
      format.json { head :no_content }
    end
  end

  private

  def project_params
    params.require(:project).permit({ project_files: [] })
  end

  def add_more_files(new_files)
    existing_files = project.project_files || []
    project.project_files = existing_files.map(&:identifier) + new_files
  end

  def remove_file(file_name)
    remain_project_files = project.project_files.reject { |f| f.identifier == file_name }

    if remain_project_files.size != project.project_files.size
      project.project_files = remain_project_files.map(&:identifier)
    end
  end

  def set_tab
    @tab_name = 'Project'
  end
end

app/controllers/project/import_controller.rb
class Project::ImportController < Project::BaseController
  before_action :project_owner_only!

  def show
    @imported_tasks = project.tasks.where(id: import_session_data(:task_ids))
    @imported_task_count = import_session_data(:task_count)
    @imported_note_count = import_session_data(:note_count)
    @imported_comment_count = import_session_data(:comment_count)
  end

  def new
  end

  def create
    file = params[:file]
    data = parse_json_file(file)

    validator = ProjectImportValidator.new(file, data)

    unless validator.valid?
      redirect_to new_project_import_path(project), alert: validator.errors.first
      return
    end

    perform_import(data)
  rescue JSON::ParserError
    redirect_to new_project_import_path(project), alert: 'Invalid JSON file.'
  rescue ActiveRecord::RecordInvalid => e
    redirect_to new_project_import_path(project), alert: e.message
  rescue ProjectImportService::ImportFormatError => e
    redirect_to new_project_import_path(project), alert: e.message
  rescue StandardError
    redirect_to new_project_import_path(project),
                alert: 'An error occurred during import. Please try again.'
  end

  private

  def parse_json_file(file)
    return nil if file.nil?

    JSON.parse(file.read)
  end

  def perform_import(data)
    import_service = ProjectImportService.new(project, data, current_user)
    import_service.import!

    store_import_stats(import_service.import_stats)

    redirect_to project_import_path(project), notice: 'Data imported successfully.'
  end

  def store_import_stats(stats)
    session[:imported_task_ids] = stats[:task_ids]
    session[:imported_task_count] = stats[:task_count]
    session[:imported_note_count] = stats[:note_count]
    session[:imported_comment_count] = stats[:comment_count]
  end

  def import_session_data(key)
    session.delete("imported_#{key}".to_sym) || default_value_for(key)
  end

  def default_value_for(key)
    key == :task_ids ? [] : 0
  end
end

app/controllers/project/links_controller.rb
class Project::LinksController < Project::BaseController
  before_action :set_link, only: %i[ show destroy ]
  before_action :set_tab

  def index
  end

  def show
  end

  def new
    @link = Link.new
  end

  def create
    @link = project.links.new(link_params)
    @link.user = current_user

    respond_to do |format|
      if @link.save
        format.html { redirect_to project_links_path(@project), notice: "Link was successfully created." }
        format.json { render :show, status: :created, location: @link }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @link.destroy!

    respond_to do |format|
      format.html { redirect_to project_links_path(@project) }
      format.json { head :no_content }
    end
  end

  private

  def set_link
    @link = project.links.find(params[:id])
  end

  def link_params
    params.require(:link).permit(:title, :url, :user_id, :project_id)
  end

  def set_tab
    @tab_name = 'Project'
  end
end

app/controllers/project/notes_controller.rb
class Project::NotesController < Project::BaseController
  before_action :set_note, only: %i[ show destroy edit update history version]
  before_action :set_tab, only: %i[ show edit index history version ]

  def index
  end

  def show
  end

  def history
    @versions = @note.versions.order(created_at: :desc)

    user_ids = @versions.map(&:whodunnit)
    user_ids.compact!
    user_ids.uniq!
    users_by_id = User.where(id: user_ids).index_by(&:id)

    @users_by_version = @versions.each_with_object({}) do |version, hash|
      hash[version.id] = users_by_id[version.whodunnit.to_i]
    end
  end

  def version
    @version = @note.versions.find(params[:version_id])
  end

  def new
    @note = project.notes.new(title: 'New Note')
    @note.user = current_user

    if @note.save
      @project.add_activity(current_user, 'created', @note)

      redirect_to edit_project_note_path(@project, @note)
    else
      record_not_found
    end
  end

  def edit
  end

  def update
    @note.update(note_params)

    respond_to do |format|
      format.html { redirect_to edit_project_note_path(@project, @note), notice: 'Saved' }
    end
  end

  def destroy
    @note.destroy!
    @project.add_activity(current_user, 'removed', @note)

    respond_to do |format|
      format.html { redirect_to project_notes_path(@project) }
      format.json { head :no_content }
    end
  end

  private

  def set_note
    @note = project.notes.find(params[:id])
  end

  def set_tab
    @tab_name = 'Project'
  end

  def note_params
    params.require(:note).permit(:title, :content)
  end
end

app/controllers/project/pins_controller.rb
class Project::PinsController < Project::BaseController
  def create
    current_user.pinned_projects << project unless current_user.pinned_projects.include?(project)

    redirect_to project_path(project), notice: "Project pinned successfully."
  end

  def destroy
    current_user.pinned_projects.delete(project)

    redirect_to project_path(project), notice: "Project unpinned successfully."
  end
end

app/controllers/project/users_controller.rb
class Project::UsersController < Project::BaseController
  before_action :not_personal
  before_action :project_owner_only!, except: [:index, :leave]
  before_action :set_tab

  def index
    @recent_activity = project.activities.includes(:user).order(id: :desc).limit(20)
  end

  def invite
  end

  def add_member
    user = User.find_by(email: params[:email])

    if user
      if user.allow_invites
        if project.user != user && project.users.exclude?(user)
          if project.users << user
            project.add_activity(current_user, 'invited', user)

            redirect_to project_users_path(project)
            return
          else
            error = 'User could not be added.'
          end
        else
          error = 'User is already added to the project'
        end
      else
        error = 'User disabled invitations'
      end
    else
      error = 'User not found'
    end

    redirect_to invite_project_users_path(@project), alert: error
  end

  def destroy
    user = User.find(params[:id])

    if project.users.include?(user)
      project.users.delete(user)

      redirect_to project_users_path(project), notice: 'User was successfully removed.'
    else
      redirect_to project_users_path(project), alert: 'User could not be found or removed.'
    end
  end

  def leave
    if project.users.include?(current_user)
      project.users.delete(current_user)

      redirect_to projects_path, notice: 'You left the project.'
    end
  end

  private

  def not_personal
    redirect_to root_path if project.personal?
  end

  def set_tab
    @tab_name = 'Team'
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  DONE_TASKS = 8

  before_action :authenticate_user!
  before_action :project, only: %i[ show edit update destroy]
  before_action :authorize_access, except: [:index, :new, :create]
  before_action :authorize_update, only: [:edit, :update, :destroy]

  rescue_from ActiveRecord::RecordNotFound, with: :record_not_found

  layout :set_layout

  # GET /projects or /projects.json
  def index
    @pinned_projects = current_user.pinned_projects
    @projects = current_user.all_active_projects - @pinned_projects
    @archived_projects = current_user.projects.archived.page(params[:page]).per(39)
  end

  # GET /projects/1 or /projects/1.json
  def show
    @tab_name = 'Project'

    today = Date.current
    @tasks_due = @project.tasks.todo.with_due_date.where(due_date: ..(today + 1.month)).includes(:assigned_user, :comments).order(due_date: :asc)

    @tasks_todo = @project.tasks.todo.where.not(id: @tasks_due).includes(:assigned_user, :comments).basic_order
    @tasks_done = @project.tasks.done.includes(:assigned_user, :comments).order(updated_at: :desc).limit(DONE_TASKS)
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
    @tab_name = 'Settings'
  end

  # POST /projects or /projects.json
  def create
    @project = current_user.projects.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to project_url(@project), notice: "Project was successfully created." }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1 or /projects/1.json
  def update
    @tab_name = 'Settings'

    respond_to do |format|
      if @project.update(project_params)
        # Remove from favourites when archiving
        if project_params[:archived] == 'true' && @project.archived?
          @project.pins.destroy_all
        end

        format.html { redirect_back fallback_location: project_url(@project), notice: "Project was successfully updated." }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1 or /projects/1.json
  def destroy
    @project.destroy!

    respond_to do |format|
      format.html { redirect_to projects_url, notice: "Project was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def project
    @project ||= Project.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def project_params
    params.require(:project).permit(:name, :archived)
  end

  def authorize_update
    if current_user.owns?(project)
      true
    else
      raise ActiveRecord::RecordNotFound
    end
  end

  def set_layout
    case action_name
    when 'show', 'edit', 'update' then 'project'
    else
      'application'
    end
  end
end

app/helpers/project/export_helper.rb
module Project::ExportHelper
end

app/helpers/project/import_helper.rb
module Project::ImportHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
  def project_tabs(project, selected = nil)
    tabs = [
      { name: 'Project', path: project_path(project) },
      { name: 'Tasks', path: project_tasks_path(project) }
    ]

    unless project.personal?
      tabs << { name: 'Team', path: project_users_path(project) }
    end

    if project.user == current_user
      tabs << { name: 'Settings', path: edit_project_path(project) }
    end

    render_tabs(tabs, selected)
  end

  def project_nav_link(path, label, count = nil, compact: false)
    link_to path, class: "flex flex-col bg-gray-400/5 p-6 dark:bg-white/5" do
      content = tag.dt(label, class: "text-xs/5 font-semibold text-gray-600 dark:text-gray-300")

      unless compact
        content += tag.dd(count, class: "order-first text-2xl font-semibold tracking-tight text-gray-900 dark:text-white")
      end

      content
    end
  end
end

app/views/projects/_files_section.html.erb
<% if file_storage_enabled? %>
  <div class="resource-container">
    <div class="resource-header">
      <div class="flex items-center justify-between w-full">
        <div class="flex items-center">
          <h2 class="resource-title">Files</h2>
        </div>
        <%= link_to new_project_file_path(project), class: "btn-base-sm" do %>
          Upload File
        <% end %>
      </div>
    </div>

    <% if project.project_files.any? %>
      <div class="resource-list">
        <% project.project_files.each do |project_file| %>
          <%= render 'project/files/file', project_file: project_file %>
        <% end %>
      </div>
    <% else %>
      <div class="resource-empty-state">
        <svg class="resource-empty-icon" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="1" d="M19.5 14.25v-2.625a3.375 3.375 0 00-3.375-3.375h-1.5A1.125 1.125 0 0113.5 7.125v-1.5a3.375 3.375 0 00-3.375-3.375H8.25m6.75 12H9m1.5-12H5.625c-.621 0-1.125.504-1.125 1.125v17.25c0 .621.504 1.125 1.125 1.125h12.75c.621 0 1.125-.504 1.125-1.125V11.25a9 9 0 00-9-9z" />
        </svg>
        <h3 class="resource-empty-title">No files</h3>
        <p class="resource-empty-description">Upload your first project file to get started.</p>
        <div class="resource-empty-action">
          <%= link_to new_project_file_path(project), class: "btn-base" do %>
            Upload a file
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

app/views/projects/_form.html.erb
<%= form_with(model: project, class: "contents") do |form| %>
  <%= render "shared/errors", resource: project %>

  <div class="mt-5">
    <%= form.label :name, class:"dark:text-gray-200" %>
    <%= form.text_field :name, required: true, autocomplete: 'off', class: "block base-input w-full mt-2" %>
  </div>

  <div class="mt-5">
    <%= form.submit class: "btn-base" %>
  </div>
<% end %>

app/views/projects/_links_section.html.erb
<div class="resource-container">
  <div class="resource-header">
    <div class="flex items-center justify-between w-full">
      <div class="flex items-center">
        <h2 class="resource-title">Links</h2>
      </div>
      <%= link_to new_project_link_path(project), class: "btn-base-sm" do %>
        Add Link
      <% end %>
    </div>
  </div>

  <% if project.links.any? %>
    <div class="resource-list">
      <% project.links.each do |link| %>
        <%= render 'project/links/link', link: link %>
      <% end %>
    </div>
  <% else %>
    <div class="resource-empty-state">
      <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" class="resource-empty-icon">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="1" d="M13.19 8.688a4.5 4.5 0 011.242 7.244l-4.5 4.5a4.5 4.5 0 01-6.364-6.364l1.757-1.757m13.35-.622l1.757-1.757a4.5 4.5 0 00-6.364-6.364l-4.5 4.5a4.5 4.5 0 001.242 7.244" />
      </svg>
      <h3 class="resource-empty-title">No links</h3>
      <p class="resource-empty-description">Add your first project link to get started.</p>
      <div class="resource-empty-action">
        <%= link_to new_project_link_path(project), class: "btn-base" do %>
          Add a link
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/projects/_team.html.erb
<div class="mb-4">
  <dt class="text-sm font-medium leading-7 text-gray-900 dark:text-gray-200 mb-2 pb-2 border-b dark:border-gray-800">Users</dt>
  <ul role="list">
    <li class="flex justify-between py-2 px-4">
      <div class="flex min-w-0 gap-x-4">
        <%= avatar_tag(@project.user, "h-6 w-6 flex-none rounded-full bg-gray-200 dark:bg-gray-800") %>
        <div class="min-w-0 flex-auto">
          <p class="text-sm leading-6 text-gray-600 dark:text-gray-400"><%= link_to @project.user.email, project_tasks_path(@project, assigned_user_id: @project.user_id) %></p>
        </div>
      </div>
    </li>

    <% @project.users.each do |user| %>
      <li id="project_<%= dom_id user %>" class="flex justify-between py-2 px-4">
        <div class="flex min-w-0 gap-x-4">
          <%= avatar_tag(user, "h-6 w-6 flex-none rounded-full bg-gray-200 dark:bg-gray-800") %>
          <div class="min-w-0 flex-auto">
            <p class="text-sm leading-6 text-gray-600 dark:text-gray-400"><%= link_to user.email, project_tasks_path(@project, assigned_user_id: user.id) %></p>
          </div>
        </div>

        <div class="ml-4 flex-shrink-0">
          <%= button_to project_user_path(@project, user), method: :delete, title: "Remove", data: { turbo_confirm: 'Remove team member? Are you sure?' } do %>
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-3 h-3 text-gray-400 dark:text-gray-600 dark:hover:text-indigo-300 mt-1">
              <path stroke-linecap="round" stroke-linejoin="round" d="m14.74 9-.346 9m-4.788 0L9.26 9m9.968-3.21c.342.052.682.107 1.022.166m-1.022-.165L18.16 19.673a2.25 2.25 0 0 1-2.244 2.077H8.084a2.25 2.25 0 0 1-2.244-2.077L4.772 5.79m14.456 0a48.108 48.108 0 0 0-3.478-.397m-12 .562c.34-.059.68-.114 1.022-.165m0 0a48.11 48.11 0 0 1 3.478-.397m7.5 0v-.916c0-1.18-.91-2.164-2.09-2.201a51.964 51.964 0 0 0-3.32 0c-1.18.037-2.09 1.022-2.09 2.201v.916m7.5 0a48.667 48.667 0 0 0-7.5 0" />
            </svg>
          <% end %>
        </div>
      </li>
    <% end %>

    <li class="flex justify-between py-2 px-4">
      <div class="flex min-w-0 gap-x-4">
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="h-6 w-6 flex-shrink-0 fill-gray-200 dark:fill-gray-800 text-gray-400 dark:text-gray-600">
          <path stroke-linecap="round" stroke-linejoin="round" d="M12 4.5v15m7.5-7.5h-15" />
        </svg>
        <div class="min-w-0 flex-auto">
          <%= link_to "Invite people", invite_project_users_path(@project), class: "text-sm leading-6 text-gray-600 dark:text-gray-400  hover:text-indigo-700 dark:hover:text-indigo-300" %>
        </div>
      </div>
    </li>
  </ul>
</div>

app/views/projects/edit.html.erb
<div class=" space-y-6">
  <%= display_flash %>

  <div class="resource-container">
    <!-- Header -->
    <div class="resource-header">
      <div>
        <h3 class="resource-title">Project Settings</h3>
        <p class="resource-description">Manage your project settings and preferences.</p>
      </div>
    </div>

    <div class="divide-y divide-gray-200 dark:divide-gray-700 space-y-0">
      <!-- Project Name Section -->
      <% unless @project.personal? %>
        <div class="p-4">
          <div class="mb-4">
            <h4 class="resource-subtitle mb-0">Name</h4>
            <p class="mt-1 text-secondary">
              Change the name of your project.
            </p>
          </div>

          <%= form_with(model: @project, class: "mt-4") do |form| %>
            <%= render "shared/errors", resource: @project %>

            <div>
              <%= form.text_field :name, required: true, class: "base-input w-full" %>
            </div>

            <div class="mt-4">
              <%= form.submit "Save Changes", class: "btn-base" %>
            </div>
          <% end %>
        </div>
      <% end %>

      <!-- Import/Export Section -->
      <div class="p-4">
        <div class="mb-4">
          <h4 class="resource-subtitle mb-0">Import and Export</h4>
          <p class="mt-1 text-secondary">
            Export your project data as a JSON file including all tasks, notes, and comments, then import it into another project.
          </p>
        </div>

        <div class="flex space-x-3">
          <%= button_to "Export Tasks", project_export_path(@project, format: :json), method: :post, class: "btn-base", form: { 'data-turbo': 'false', class: 'inline-block' } %>
          <%= link_to "Import Tasks", new_project_import_path(@project), class: "btn-base" %>
        </div>
      </div>

      <!-- Archive Section -->
      <div class="p-4">
        <div class="mb-4">
          <h4 class="resource-subtitle mb-0">Project Status</h4>
          <p class="mt-1 text-secondary">
            <% if @project.archived? %>
              This project is archived. Unarchiving it will allow the creation of new tasks.
            <% else %>
              Archiving this project will prevent the creation of new tasks. This action is easily reversible.
            <% end %>
          </p>
        </div>

        <% if @project.archived? %>
          <%= button_to 'Unarchive Project', project_path(@project, project: { archived: false }), method: :patch, class: "btn-primary", data: { confirm: "Are you sure you want to unarchive this project?" } %>
        <% else %>
          <%= button_to 'Archive Project', project_path(@project, project: { archived: true }), method: :patch, class: "btn-base", data: { confirm: "Are you sure you want to archive this project?" } %>
        <% end %>
      </div>
    </div>
  </div>

  <!-- Delete Project Section -->
  <div class="resource-container">
    <div class="resource-header">
      <div>
        <h3 class="resource-title text-red-600 dark:text-red-400">Delete Project</h3>
        <p class="resource-description">Permanently delete this project and all its data.</p>
      </div>
    </div>

    <div class="p-4">
      <div class="mb-4">
        <p class="text-secondary">
          Deleting this project will permanently erase all data. Please consider exporting tasks before proceeding.
        </p>
      </div>

      <%= button_to "Delete this project", @project, method: :delete, data: { turbo_confirm: 'Remove the project? Are you sure?' }, class: "btn-remove" %>
    </div>
  </div>
</div>

app/views/projects/index.html.erb
<div>
  <% content_for :title, "Projects" %>

  <% content_for :subnav do %>
    <nav class="nav-container">
      <div class="flex flex-wrap nav-controls">
        <%= home_tabs "Projects" %>
        <%= link_to "New Project", new_project_path, class: "btn-base" %>
      </div>
    </nav>
  <% end %>

  <%= display_flash %>

  <div>
    <div class="space-y-4">
      <% if @pinned_projects.present? %>
        <div class="resource-container">
          <div>
            <ul id="pinned-projects" role="list" class="resource-list">
              <% @pinned_projects.each do |project| %>
                <%= render project, pinned: true %>
              <% end %>
            </ul>
          </div>
        </div>
      <% end %>

      <% if @projects.present? %>
        <div class="resource-container">
          <div>
            <ul id="projects" role="list" class="resource-list">
              <% @projects.each do |project| %>
                <%= render project %>
              <% end %>
            </ul>
          </div>
        </div>
      <% end %>

      <% if @archived_projects.any? %>
        <div class="resource-container">
          <div>
            <ul id="archived-projects" role="list" class="resource-list">
              <% @archived_projects.each do |project| %>
                <%= render project %>
              <% end %>
            </ul>

            <% if @archived_projects.total_pages > 1 %>
              <div class="mt-4">
                <%= paginate @archived_projects %>
              </div>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/projects/new.html.erb
<div class="">
  <div class="resource-container">
    <div class="resource-header">
      <div>
        <h1 class="resource-title">New project</h1>
        <p class="resource-description">Anything can be a project, whether it's brewing a cup of coffee or constructing a rocketship. Just start with a name.</p>
      </div>
    </div>

    <div class="p-4 pt-0">
      <%= render "form", project: @project %>
    </div>
  </div>
</div>