config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  resources :projects do

    resources :tasks, controller: 'project/tasks' do
      member do
        get :details
        patch :toggle_done
        patch :toggle_star

        get :changes
      end

      collection do
        get :completed
      end

      resources :comments, controller: 'project/comments', only: [:create, :destroy]
    end

    resources :links, controller: 'project/links', only: [:index, :new, :create, :show, :destroy]
    resources :notes, controller: 'project/notes' do
      member do
        get :history
        get :version
      end
    end

    resources :files, controller: 'project/files', only: [:index, :new, :create] do
      collection do
        get :download
        delete :destroy, as: 'delete'
      end
    end

    resources :users, only: [:index, :destroy], controller: 'project/users' do
      collection do
        get 'invite', to: 'project/users#invite'
        post 'add_member', to: 'project/users#add_member'
        delete 'leave', to: 'project/users#leave'
      end
    end

    resource :pins, controller: 'project/pins', only: [:create, :destroy]

    resource :activity, only: :show, controller: 'project/activity'

    resource :import, only: [:new, :create, :show], controller: 'project/import'
    resource :export, only: [:new, :create], controller: 'project/export'
  end

  namespace :admin do
    resources :users, only: [:index, :show, :edit, :update, :destroy]
  end

  get 'admin' => 'admin#index'
  get 'admin/activity', to: 'admin/activity#index'

  namespace :users do
    resource :settings, only: [:show, :update]
    resource :account, only: [:show, :update, :destroy]
  end
  get 'users/:id/avatar', to: 'users/avatars#show', as: :user_avatar

  get 'projects/:id/schedule', to: redirect { |params, _| "/projects/#{params[:id]}" }
  get 'schedule', to: redirect('/tasks')
  get 'search', to: 'search#index'
  resources :tasks, only: :index, controller: 'tasks' do
    member do
      patch :toggle_done
    end
  end

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  get "hello" => "hello#welcome"

  # Defines the root path route ("/")
  root "projects#index"
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :authenticate_admin!
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :set_tab

  layout 'admin'

  def index
    @users = User.order(id: :desc).page(params[:page]).per(50)
  end

  def show
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to admin_user_path(@user), notice: 'User updated successfully.'
    else
      flash.now[:alert] = 'Failed to update user.'
      render :edit
    end
  end

  def destroy
    if @user.destroy
      redirect_to admin_users_path, notice: 'User deleted successfully.'
    else
      redirect_to admin_users_path, alert: 'Failed to delete user.'
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:confirmed_at)
  end

  def set_tab
    @tab_name = 'Users'
  end
end

app/controllers/project/activity_controller.rb
class Project::ActivityController < Project::BaseController
  PER_PAGE = 100

  def show
    @tab_name = 'Activity'

    @records = project.activities.includes(:user).order(id: :desc).page(params[:page]).per(PER_PAGE)
  end
end

app/controllers/project/base_controller.rb
class Project::BaseController < ApplicationController
  before_action :authenticate_user!
  before_action :project
  before_action :authorize_access

  layout 'project'

  def project
    @project ||= Project.find(params[:project_id])
  end
end

app/controllers/project/comments_controller.rb
class Project::CommentsController < Project::BaseController
  before_action :set_task

  def create
    @comment = @task.comments.build(comment_params)
    @comment.user = current_user

    if @comment.save
      @project.add_activity(current_user, 'commented on', @task)

      respond_to do |format|
        format.html { redirect_to task_path, notice: 'Comment was successfully created.' }
        format.turbo_stream
      end
    else
      respond_to do |format|
        format.html { redirect_to task_path, alert: 'Comment could not be created.' }
      end
    end
  end

  def destroy
    @comment = @task.comments.find(params[:id])
    @comment.update(removed_at: Time.current)

    respond_to do |format|
      format.html { redirect_to task_path, notice: 'Comment was successfully deleted.' }
      format.turbo_stream
    end
  end

  private

  def set_task
    @task = project.tasks.find(params[:task_id])
  end

  def comment_params
    permitted = params.require(:comment).permit(:body, :attachment)
    permitted.delete(:attachment) unless file_storage_enabled?
    permitted
  end

  def task_path
    details_project_task_path(project, @task)
  end
end

app/controllers/project/export_controller.rb
class Project::ExportController < Project::BaseController
  before_action :project_owner_only!

  def new
  end

  def create
    export_service = ProjectExportService.new(project)

    respond_to do |format|
      format.json do
        send_data export_service.export_data.to_json,
                  filename: export_service.filename,
                  type: 'application/json',
                  disposition: 'attachment'
      end
    end
  end
end

app/controllers/project/files_controller.rb
class Project::FilesController < Project::BaseController
  before_action :set_tab
  before_action :require_file_storage!, only: [:new, :create]

  def index
  end

  def new
  end

  def download
    file = project.project_files.find { |f| f.identifier == params[:file] }

    if file
      if ENV['AWS_S3_BUCKET'].present?
        send_data file.read, filename: file.identifier, type: file.content_type, disposition: 'attachment'
      else
        send_file file.file.path, filename: file.file.identifier, type: file.file.content_type, disposition: 'attachment'
      end
    else
      redirect_to project_path(project), alert: 'File not found.'
    end
  end

  def create
    add_more_files(params[:project][:project_files])

    if project.save
      redirect_to project_files_path(@project), notice: 'Files were successfully uploaded.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    remove_file(params[:file])

    project.save

    respond_to do |format|
      format.html { redirect_to project_files_path(@project) }
      format.json { head :no_content }
    end
  end

  private

  def project_params
    params.require(:project).permit({ project_files: [] })
  end

  def add_more_files(new_files)
    existing_files = project.project_files || []
    project.project_files = existing_files.map(&:identifier) + new_files
  end

  def remove_file(file_name)
    remain_project_files = project.project_files.reject { |f| f.identifier == file_name }

    if remain_project_files.size != project.project_files.size
      project.project_files = remain_project_files.map(&:identifier)
    end
  end

  def set_tab
    @tab_name = 'Project'
  end
end

app/controllers/project/import_controller.rb
class Project::ImportController < Project::BaseController
  before_action :project_owner_only!

  def show
    @imported_tasks = project.tasks.where(id: import_session_data(:task_ids))
    @imported_task_count = import_session_data(:task_count)
    @imported_note_count = import_session_data(:note_count)
    @imported_comment_count = import_session_data(:comment_count)
  end

  def new
  end

  def create
    file = params[:file]
    data = parse_json_file(file)

    validator = ProjectImportValidator.new(file, data)

    unless validator.valid?
      redirect_to new_project_import_path(project), alert: validator.errors.first
      return
    end

    perform_import(data)
  rescue JSON::ParserError
    redirect_to new_project_import_path(project), alert: 'Invalid JSON file.'
  rescue ActiveRecord::RecordInvalid => e
    redirect_to new_project_import_path(project), alert: e.message
  rescue ProjectImportService::ImportFormatError => e
    redirect_to new_project_import_path(project), alert: e.message
  rescue StandardError
    redirect_to new_project_import_path(project),
                alert: 'An error occurred during import. Please try again.'
  end

  private

  def parse_json_file(file)
    return nil if file.nil?

    JSON.parse(file.read)
  end

  def perform_import(data)
    import_service = ProjectImportService.new(project, data, current_user)
    import_service.import!

    store_import_stats(import_service.import_stats)

    redirect_to project_import_path(project), notice: 'Data imported successfully.'
  end

  def store_import_stats(stats)
    session[:imported_task_ids] = stats[:task_ids]
    session[:imported_task_count] = stats[:task_count]
    session[:imported_note_count] = stats[:note_count]
    session[:imported_comment_count] = stats[:comment_count]
  end

  def import_session_data(key)
    session.delete("imported_#{key}".to_sym) || default_value_for(key)
  end

  def default_value_for(key)
    key == :task_ids ? [] : 0
  end
end

app/controllers/project/links_controller.rb
class Project::LinksController < Project::BaseController
  before_action :set_link, only: %i[ show destroy ]
  before_action :set_tab

  def index
  end

  def show
  end

  def new
    @link = Link.new
  end

  def create
    @link = project.links.new(link_params)
    @link.user = current_user

    respond_to do |format|
      if @link.save
        format.html { redirect_to project_links_path(@project), notice: "Link was successfully created." }
        format.json { render :show, status: :created, location: @link }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @link.destroy!

    respond_to do |format|
      format.html { redirect_to project_links_path(@project) }
      format.json { head :no_content }
    end
  end

  private

  def set_link
    @link = project.links.find(params[:id])
  end

  def link_params
    params.require(:link).permit(:title, :url, :user_id, :project_id)
  end

  def set_tab
    @tab_name = 'Project'
  end
end

app/controllers/project/notes_controller.rb
class Project::NotesController < Project::BaseController
  before_action :set_note, only: %i[ show destroy edit update history version]
  before_action :set_tab, only: %i[ show edit index history version ]

  def index
  end

  def show
  end

  def history
    @versions = @note.versions.order(created_at: :desc)

    user_ids = @versions.map(&:whodunnit)
    user_ids.compact!
    user_ids.uniq!
    users_by_id = User.where(id: user_ids).index_by(&:id)

    @users_by_version = @versions.each_with_object({}) do |version, hash|
      hash[version.id] = users_by_id[version.whodunnit.to_i]
    end
  end

  def version
    @version = @note.versions.find(params[:version_id])
  end

  def new
    @note = project.notes.new(title: 'New Note')
    @note.user = current_user

    if @note.save
      @project.add_activity(current_user, 'created', @note)

      redirect_to edit_project_note_path(@project, @note)
    else
      record_not_found
    end
  end

  def edit
  end

  def update
    @note.update(note_params)

    respond_to do |format|
      format.html { redirect_to edit_project_note_path(@project, @note), notice: 'Saved' }
    end
  end

  def destroy
    @note.destroy!
    @project.add_activity(current_user, 'removed', @note)

    respond_to do |format|
      format.html { redirect_to project_notes_path(@project) }
      format.json { head :no_content }
    end
  end

  private

  def set_note
    @note = project.notes.find(params[:id])
  end

  def set_tab
    @tab_name = 'Project'
  end

  def note_params
    params.require(:note).permit(:title, :content)
  end
end

app/controllers/project/pins_controller.rb
class Project::PinsController < Project::BaseController
  def create
    current_user.pinned_projects << project unless current_user.pinned_projects.include?(project)

    redirect_to project_path(project), notice: "Project pinned successfully."
  end

  def destroy
    current_user.pinned_projects.delete(project)

    redirect_to project_path(project), notice: "Project unpinned successfully."
  end
end

app/controllers/project/users_controller.rb
class Project::UsersController < Project::BaseController
  before_action :not_personal
  before_action :project_owner_only!, except: [:index, :leave]
  before_action :set_tab

  def index
    @recent_activity = project.activities.includes(:user).order(id: :desc).limit(20)
  end

  def invite
  end

  def add_member
    user = User.find_by(email: params[:email])

    if user
      if user.allow_invites
        if project.user != user && project.users.exclude?(user)
          if project.users << user
            project.add_activity(current_user, 'invited', user)

            redirect_to project_users_path(project)
            return
          else
            error = 'User could not be added.'
          end
        else
          error = 'User is already added to the project'
        end
      else
        error = 'User disabled invitations'
      end
    else
      error = 'User not found'
    end

    redirect_to invite_project_users_path(@project), alert: error
  end

  def destroy
    user = User.find(params[:id])

    if project.users.include?(user)
      project.users.delete(user)

      redirect_to project_users_path(project), notice: 'User was successfully removed.'
    else
      redirect_to project_users_path(project), alert: 'User could not be found or removed.'
    end
  end

  def leave
    if project.users.include?(current_user)
      project.users.delete(current_user)

      redirect_to projects_path, notice: 'You left the project.'
    end
  end

  private

  def not_personal
    redirect_to root_path if project.personal?
  end

  def set_tab
    @tab_name = 'Team'
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  DONE_TASKS = 8

  before_action :authenticate_user!
  before_action :project, only: %i[ show edit update destroy]
  before_action :authorize_access, except: [:index, :new, :create]
  before_action :authorize_update, only: [:edit, :update, :destroy]

  rescue_from ActiveRecord::RecordNotFound, with: :record_not_found

  layout :set_layout

  # GET /projects or /projects.json
  def index
    @pinned_projects = current_user.pinned_projects
    @projects = current_user.all_active_projects - @pinned_projects
    @archived_projects = current_user.projects.archived.page(params[:page]).per(39)
  end

  # GET /projects/1 or /projects/1.json
  def show
    @tab_name = 'Project'

    today = Date.current
    @tasks_due = @project.tasks.todo.with_due_date.where(due_date: ..(today + 1.month)).includes(:assigned_user, :comments).order(due_date: :asc)

    @tasks_todo = @project.tasks.todo.where.not(id: @tasks_due).includes(:assigned_user, :comments).basic_order
    @tasks_done = @project.tasks.done.includes(:assigned_user, :comments).order(updated_at: :desc).limit(DONE_TASKS)
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
    @tab_name = 'Settings'
  end

  # POST /projects or /projects.json
  def create
    @project = current_user.projects.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to project_url(@project), notice: "Project was successfully created." }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1 or /projects/1.json
  def update
    @tab_name = 'Settings'

    respond_to do |format|
      if @project.update(project_params)
        # Remove from favourites when archiving
        if project_params[:archived] == 'true' && @project.archived?
          @project.pins.destroy_all
        end

        format.html { redirect_back fallback_location: project_url(@project), notice: "Project was successfully updated." }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1 or /projects/1.json
  def destroy
    @project.destroy!

    respond_to do |format|
      format.html { redirect_to projects_url, notice: "Project was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def project
    @project ||= Project.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def project_params
    params.require(:project).permit(:name, :archived)
  end

  def authorize_update
    if current_user.owns?(project)
      true
    else
      raise ActiveRecord::RecordNotFound
    end
  end

  def set_layout
    case action_name
    when 'show', 'edit', 'update' then 'project'
    else
      'application'
    end
  end
end

app/views/project/users/index.html.erb
<div class=" space-y-6">
  <!-- Team Members Section -->
  <div class="resource-container">
    <!-- Header with actions -->
    <div class="resource-header">
      <div>
        <h3 class="resource-title">Team Members</h3>
        <p class="resource-description">Manage your project team and collaborate with others.</p>
      </div>
      <div>
        <% if current_user == @project.owner %>
          <%= link_to 'Invite People', invite_project_users_path(@project), class: "btn-base-sm" %>
        <% elsif @project.users.include?(current_user) %>
          <%= button_to 'Leave Project', leave_project_users_path(@project), method: :delete,
            class: "btn-base-sm",
            data: { turbo_confirm: 'Are you sure you want to leave this project?' } %>
        <% end %>
      </div>
    </div>

    <!-- Team members list -->
    <div class="">
      <% if @project.users.any? || @project.user == current_user %>
        <ul role="list" class="resource-list">
          <!-- Project Owner -->
          <li class="flex justify-between">
            <div class="flex min-w-0 items-center">
              <%= avatar_tag(@project.user, "h-10 w-10 flex-none rounded-full") %>
              <div class="ml-4 min-w-0 flex-1">
                <div class="flex items-center">
                  <%= link_to @project.user.email, project_tasks_path(@project, assigned_user_id: @project.user_id), class: "link-primary list-text-primary truncate" %>
                </div>
                <div class="mt-1">
                  <span class="inline-flex items-center rounded-md bg-violet-50 dark:bg-violet-900/30 px-2 py-1 text-xs font-medium text-violet-700 dark:text-violet-300 ring-1 ring-inset ring-violet-600/20 dark:ring-violet-500/30">
                    Project Owner
                  </span>
                </div>
              </div>
            </div>
          </li>

          <!-- Team Members -->
          <% @project.users.each do |user| %>
            <li id="project_<%= dom_id user %>" class="flex justify-between">
              <div class="flex min-w-0 items-center">
                <%= avatar_tag(user, "h-10 w-10 flex-none rounded-full") %>
                <div class="ml-4 min-w-0 flex-1">
                  <div class="flex items-center">
                    <%= link_to user.email, project_tasks_path(@project, assigned_user_id: user.id), class: "link-primary list-text-primary truncate" %>
                  </div>
                  <div class="mt-1 list-text-secondary">
                    Team Member
                  </div>
                </div>
              </div>

              <% if current_user == @project.owner %>
                <div class="flex-shrink-0 flex items-center space-x-2">
                  <%= button_to project_user_path(@project, user), method: :delete,
                    class: "inline-flex items-center p-1.5",
                    title: "Remove",
                    data: { turbo_confirm: 'Remove team member? Are you sure?' } do %>
                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-5 h-5">
                      <path stroke-linecap="round" stroke-linejoin="round" d="m14.74 9-.346 9m-4.788 0L9.26 9m9.968-3.21c.342.052.682.107 1.022.166m-1.022-.165L18.16 19.673a2.25 2.25 0 0 1-2.244 2.077H8.084a2.25 2.25 0 0 1-2.244-2.077L4.772 5.79m14.456 0a48.108 48.108 0 0 0-3.478-.397m-12 .562c.34-.059.68-.114 1.022-.165m0 0a48.11 48.11 0 0 1 3.478-.397m7.5 0v-.916c0-1.18-.91-2.164-2.09-2.201a51.964 51.964 0 0 0-3.32 0c-1.18.037-2.09 1.022-2.09 2.201v.916m7.5 0a48.667 48.667 0 0 0-7.5 0" />
                    </svg>
                  <% end %>
                </div>
              <% end %>
            </li>
          <% end %>
        </ul>
      <% else %>
        <div class="resource-empty-state">
          <svg xmlns="http://www.w3.org/2000/svg" class="resource-empty-icon" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="1" d="M15 19.128a9.38 9.38 0 0 0 2.625.372 9.337 9.337 0 0 0 4.121-.952 4.125 4.125 0 0 0-7.533-2.493M15 19.128v-.003c0-1.113-.285-2.16-.786-3.07M15 19.128v.106A12.318 12.318 0 0 1 8.624 21c-2.331 0-4.512-.645-6.374-1.766l-.001-.109a6.375 6.375 0 0 1 11.964-3.07M12 6.375a3.375 3.375 0 1 1-6.75 0 3.375 3.375 0 0 1 6.75 0Zm8.25 2.25a2.625 2.625 0 1 1-5.25 0 2.625 2.625 0 0 1 5.25 0Z" />
          </svg>
          <h3 class="resource-empty-title">No team members</h3>
          <p class="resource-empty-description">Start collaborating by inviting people to your project.</p>
          <% if current_user == @project.owner %>
            <div class="resource-empty-action">
              <%= link_to invite_project_users_path(@project), class: "btn-base" do %>
                Invite people
              <% end %>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>

  <!-- Recent Activity Section -->
  <div class="resource-container">
    <div class="resource-header">
      <div class="flex items-center justify-between w-full">
        <div class="flex items-center">
          <h2 class="resource-title">Recent Activity</h2>
        </div>
        <%= link_to project_activity_path(@project), class: "btn-base-sm" do %>
          View all activity
        <% end %>
      </div>
    </div>

    <% if @recent_activity.any? %>
      <div class="px-4 py-4 sm:px-6">
        <ol class="relative border-l border-base space-y-4">
          <% @recent_activity.each do |record| %>
            <%= render 'project/activity/record', record: record %>
          <% end %>
        </ol>
      </div>
    <% else %>
      <div class="resource-empty-state">
        <svg xmlns="http://www.w3.org/2000/svg" class="resource-empty-icon" fill="none" viewBox="0 0 24 24" stroke="currentColor">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="1" d="M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z" />
        </svg>
        <h3 class="resource-empty-title">No activity yet</h3>
        <p class="resource-empty-description">Activity will appear here as you and your team work on this project.</p>
      </div>
    <% end %>
  </div>
</div>

app/views/project/users/invite.html.erb
<div class="">
  <div class="resource-container">
    <div class="resource-header">
      <div>
        <h1 class="resource-title">Invite Team Member</h1>
        <p class="resource-description">
          The user must have an account in the application to be added to the project.
        </p>
      </div>
    </div>

    <div class="p-4">
      <%= form_with url: add_member_project_users_path(@project), method: :post, class: "space-y-6" do |form| %>
        <%= render "shared/flash" %>

        <div>
          <%= form.label :email, "User Email", class: "block text-sm font-medium text-gray-900 dark:text-gray-200 mb-2" %>
          <div class="relative">
            <div class="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
              <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-5 h-5 text-gray-400 dark:text-gray-500">
                <path stroke-linecap="round" stroke-linejoin="round" d="M21.75 6.75v10.5a2.25 2.25 0 0 1-2.25 2.25h-15a2.25 2.25 0 0 1-2.25-2.25V6.75m19.5 0A2.25 2.25 0 0 0 19.5 4.5h-15a2.25 2.25 0 0 0-2.25 2.25m19.5 0v.243a2.25 2.25 0 0 1-1.07 1.916l-7.5 4.615a2.25 2.25 0 0 1-2.36 0L3.32 8.91a2.25 2.25 0 0 1-1.07-1.916V6.75" />
              </svg>
            </div>
            <%= form.email_field :email, required: true, class: "block w-full base-input pl-10", placeholder: "user@example.com" %>
          </div>
        </div>

        <div class="pt-4 border-t border-base">
          <%= form.submit "Add team member", class: "btn-base" %>
        </div>
      <% end %>
    </div>
  </div>
</div>